const students = [
  { image: "", name: "Abdulla Adnan", GPA: "" },
  { image: "", name: "Abiral Bhusal", GPA: "" },
  { image: "", name: "Amrit Acharya", GPA: "" },
  { image: "", name: "Anamika Basnet", GPA: "" },
  { image: "", name: "Anmol Gurung", GPA: "" },
  { image: "", name: "Asfak Mohammad Dhobi", GPA: "" },
  { image: "", name: "Bhuwan Nepali", GPA: "" },
  { image: "", name: "Bibek Shrestha", GPA: "" },
  { image: "", name: "Bikash Somai Magar", GPA: "" },
  { image: "", name: "Bipasna Poudel", GPA: "" },
  { image: "", name: "Bipshika Adhikari", GPA: "" },
  { image: "", name: "Elesh Pandey", GPA: "" },
  { image: "", name: "Madhav Khanal Chhetri", GPA: "" },
  { image: "", name: "Mohammad Arif Dhobi", GPA: "" },
  { image: "", name: "Mohammad Shahid Musalman", GPA: "" },
  { image: "", name: "Narmada Poudel", GPA: "" },
  { image: "", name: "Nischal Khadka Chhetri", GPA: "" },
  { image: "", name: "Prakriti Bhattarai", GPA: "" },
  { image: "", name: "Rijan Kandel", GPA: "" },
  { image: "", name: "Rijan Rayamajhi", GPA: "" },
  { image: "", name: "Rishab Thapa", GPA: "" },
  { image: "", name: "Rojan Thapa", GPA: "" },
  { image: "", name: "Shristi Poudel", GPA: "" },
  { image: "", name: "Sumitra Belbase", GPA: "" }
];